In [220]:
import numpy as np

### Learning array in numpy

In [221]:
### 1d array(one dimensoin array)

array_1d = np.array([1,2,3,4,5,6])
array_1d

array([1, 2, 3, 4, 5, 6])

### Two dimensional array

In [222]:
array_2d = np.array([[2,3,4],[1,2,3],[5,6,7]])
print(array_2d)

[[2 3 4]
 [1 2 3]
 [5 6 7]]


### Three dimentional array
-->collection of 2d array

In [223]:
array_3d =   np.array([[[1,2,3],
                        [2,4,5],
                        [4,5,6]],
                        [[2,3,4],
                        [5,6,7],
                        [8,9,7]]])
print(array_3d)

[[[1 2 3]
  [2 4 5]
  [4 5 6]]

 [[2 3 4]
  [5 6 7]
  [8 9 7]]]


### To check the dimension of array

In [224]:
array_3d.ndim

3

In [225]:
array_2d.ndim

2

In [226]:
array_1d.ndim

1

### One dimension array using arange

In [227]:
array_1d = np.arange(1,11)
print(array_1d)

[ 1  2  3  4  5  6  7  8  9 10]


In [228]:
array_1d = np.arange(1,101,2)
print(array_1d)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


### Linespace method

In [229]:
array_1d = np.linspace(1,10,10)
print(array_1d)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [230]:
array_1d = np.linspace(1,5,10)
print(array_1d)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


### Size of array


In [231]:
np.size(array_1d)

10

In [232]:
np.size(array_2d)

9

In [233]:
np.size(array_3d)

18

### multiply and sum in array 

In [234]:
array_1 = np.array([1,2,3,4])
array_2 = np.array([5,2,3,4])
print(array_1 * array_2)

[ 5  4  9 16]


In [235]:
array_1 = np.array([1,2,3,4])
array_2 = np.array([5,2,3,4])
print(array_1 + array_2)

[6 4 6 8]


In [236]:
np.shape(array_1d)

(10,)

In [237]:
np.shape(array_2d)

(3, 3)

In [238]:
np.shape(array_3d)

(2, 3, 3)

### multiplication in numpy array


In [239]:
array1 = np.array([1,2,3])
array2 = np.array([2,3,4])
product = array1 @ array2
print(product)

20


### concatination in numpy array


In [240]:
array1 = np.array([1,2,3])
array2 = np.array([1,2,4])
array3 = np.concatenate((array1,array2))
print(array3)


[1 2 3 1 2 4]


### For two dimentional array

In [241]:
arr2d_1 = np.array([[1,2,3,4],
                    [5,6,7,8],
                    [6,9,7,3]])
arr2d_2 = np.array([[1,5,3,4],
                    [5,6,9,8],
                    [6,1,7,3]])
array3 = np.concatenate((arr2d_1,arr2d_2), axis=0)
print(array3)

[[1 2 3 4]
 [5 6 7 8]
 [6 9 7 3]
 [1 5 3 4]
 [5 6 9 8]
 [6 1 7 3]]


In [242]:
arr2d_1 = np.array([[1,2,3,4],
                    [5,6,7,8],
                    [6,9,7,3]])
arr2d_2 = np.array([[1,5,3,4],
                    [5,6,9,8],
                    [6,1,7,3]])
array3 = np.concatenate((arr2d_1,arr2d_2), axis=1)
print(array3)

[[1 2 3 4 1 5 3 4]
 [5 6 7 8 5 6 9 8]
 [6 9 7 3 6 1 7 3]]


### hstack (h= horizontal) and vstack (v= vertical) concatenation

In [243]:
arr1 = np.array([[1,2,3,1],[4,5,8,9]])
arr2 = np.array([[2,3,4,5]])
arr3 = np.vstack((arr1,arr2))
print(arr3)
arr4 = np.array([[4],
                [3]])


[[1 2 3 1]
 [4 5 8 9]
 [2 3 4 5]]


In [244]:
print(np.hstack((arr1,arr4)))

[[1 2 3 1 4]
 [4 5 8 9 3]]


### Slicing in numpy array

In [245]:
array1 = np.arange(1,11)
print(array1)
array2 = array1[2:5]
print(array2)

[ 1  2  3  4  5  6  7  8  9 10]
[3 4 5]


### For two dimensional array

In [246]:
array3 = np.array([[2,3,4,5],
                    [1,5,6,7],
                    [2,4,6,5]])
array3.shape


(3, 4)

In [247]:
array3.ndim

2

In [248]:
#it shows specific element from 2d array [row,col] slicing
print(array3[0,0])


2


In [249]:
# slicing
print(array3[1:3,1:3])


[[5 6]
 [4 6]]


In [250]:
print(array3[0:,1:3])

[[3 4]
 [5 6]
 [4 6]]


### reshaping array in numpy

In [251]:
array3.shape

(3, 4)

In [252]:
array3.reshape(4,3)

array([[2, 3, 4],
       [5, 1, 5],
       [6, 7, 2],
       [4, 6, 5]])

In [253]:
array3.reshape(6,2)

array([[2, 3],
       [4, 5],
       [1, 5],
       [6, 7],
       [2, 4],
       [6, 5]])

In [254]:
array3.reshape(3,4)

array([[2, 3, 4, 5],
       [1, 5, 6, 7],
       [2, 4, 6, 5]])

In [255]:
array3.reshape(12)

array([2, 3, 4, 5, 1, 5, 6, 7, 2, 4, 6, 5])

In [256]:
array3.reshape(2,3,2)

array([[[2, 3],
        [4, 5],
        [1, 5]],

       [[6, 7],
        [2, 4],
        [6, 5]]])

In [257]:
array5 = np.arange(1,101)
array5.reshape(5,20)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,
         34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
         54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
         74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
         94,  95,  96,  97,  98,  99, 100]])

### Random array in numpy


In [258]:
# rand() - gives the random values between 0 and 1 
# randint() - give the random integer value with in the specified range

In [259]:
array_1 = np.random.rand(4,6)

In [260]:
print(array_1)


[[0.67673175 0.97454247 0.36883165 0.01582066 0.18886191 0.2136188 ]
 [0.9633182  0.16025251 0.96073191 0.08098219 0.38894083 0.56275665]
 [0.52642394 0.95643599 0.55541209 0.46708247 0.25871388 0.6633764 ]
 [0.15595234 0.34783981 0.99077381 0.97085863 0.5830393  0.97911864]]


In [261]:
array_2 = np.random.rand(10)
print(array_2)

[0.67149152 0.67338758 0.87167383 0.17409691 0.17953702 0.08277815
 0.04955735 0.70556918 0.01152725 0.96320912]


### randint method

In [262]:
array_3 = np.random.randint(10,15, size=(7))
print(array_3)

[13 11 10 10 10 10 14]


### spliting in numpy array

In [263]:
array1 = np.random.randint(100,500, size=(15,6))
print(array1)

[[157 138 152 169 134 444]
 [399 492 294 231 383 292]
 [327 155 349 477 457 154]
 [203 145 331 474 192 337]
 [151 230 327 366 157 117]
 [286 261 134 459 118 128]
 [427 164 208 256 496 322]
 [172 406 481 476 226 281]
 [438 155 498 334 496 323]
 [124 351 309 381 487 391]
 [272 409 169 172 419 232]
 [208 245 282 190 462 425]
 [476 289 387 470 457 317]
 [169 470 453 327 102 193]
 [455 471 471 194 447 460]]


In [264]:
array1_1, array1_2, array1_3 = np.split(array1,3,axis=0)
print(array1_1)

[[157 138 152 169 134 444]
 [399 492 294 231 383 292]
 [327 155 349 477 457 154]
 [203 145 331 474 192 337]
 [151 230 327 366 157 117]]


In [265]:
print(array1_2)

[[286 261 134 459 118 128]
 [427 164 208 256 496 322]
 [172 406 481 476 226 281]
 [438 155 498 334 496 323]
 [124 351 309 381 487 391]]


In [266]:
print(array1_3)

[[272 409 169 172 419 232]
 [208 245 282 190 462 425]
 [476 289 387 470 457 317]
 [169 470 453 327 102 193]
 [455 471 471 194 447 460]]


### Columnwise spliting 

In [267]:
array1 = np.random.randint(100,500, size=(15,6))
print(array1)

[[434 378 149 231 290 118]
 [322 262 437 238 312 149]
 [246 252 284 262 176 194]
 [465 412 176 280 356 280]
 [450 258 119 164 150 492]
 [431 429 224 441 226 352]
 [191 219 137 277 160 106]
 [153 169 403 148 344 475]
 [310 149 423 297 443 326]
 [390 201 157 188 200 170]
 [352 105 146 309 398 414]
 [251 431 217 225 296 245]
 [492 403 176 479 404 282]
 [202 320 129 173 321 139]
 [466 338 139 291 143 236]]


In [268]:
array1_1, array1_2 = np.split(array1,2, axis=1)
print(array1_1)

[[434 378 149]
 [322 262 437]
 [246 252 284]
 [465 412 176]
 [450 258 119]
 [431 429 224]
 [191 219 137]
 [153 169 403]
 [310 149 423]
 [390 201 157]
 [352 105 146]
 [251 431 217]
 [492 403 176]
 [202 320 129]
 [466 338 139]]


In [269]:
print(array1_2)

[[231 290 118]
 [238 312 149]
 [262 176 194]
 [280 356 280]
 [164 150 492]
 [441 226 352]
 [277 160 106]
 [148 344 475]
 [297 443 326]
 [188 200 170]
 [309 398 414]
 [225 296 245]
 [479 404 282]
 [173 321 139]
 [291 143 236]]


In [270]:
array1 = np.random.randint(100,500, size=(10,6))
print(array1)

[[172 356 234 434 474 191]
 [390 436 293 153 248 319]
 [277 479 214 195 285 334]
 [297 291 193 468 187 231]
 [392 359 440 285 148 351]
 [357 308 314 435 409 354]
 [242 280 444 478 443 226]
 [304 225 308 123 286 317]
 [336 222 261 445 295 226]
 [293 191 243 449 390 219]]


In [271]:
array3 = np.concatenate((array1_1, array1_2),axis=1)
print(array3)

[[434 378 149 231 290 118]
 [322 262 437 238 312 149]
 [246 252 284 262 176 194]
 [465 412 176 280 356 280]
 [450 258 119 164 150 492]
 [431 429 224 441 226 352]
 [191 219 137 277 160 106]
 [153 169 403 148 344 475]
 [310 149 423 297 443 326]
 [390 201 157 188 200 170]
 [352 105 146 309 398 414]
 [251 431 217 225 296 245]
 [492 403 176 479 404 282]
 [202 320 129 173 321 139]
 [466 338 139 291 143 236]]


### spliting array by using indexing

In [272]:
array2 = np.random.randint(100,500, size=(15,6))
print(array1)

[[172 356 234 434 474 191]
 [390 436 293 153 248 319]
 [277 479 214 195 285 334]
 [297 291 193 468 187 231]
 [392 359 440 285 148 351]
 [357 308 314 435 409 354]
 [242 280 444 478 443 226]
 [304 225 308 123 286 317]
 [336 222 261 445 295 226]
 [293 191 243 449 390 219]]


In [273]:
array2_1, array2_2 = np.split(array1,[5], axis=1)
print(array2_1)


[[172 356 234 434 474]
 [390 436 293 153 248]
 [277 479 214 195 285]
 [297 291 193 468 187]
 [392 359 440 285 148]
 [357 308 314 435 409]
 [242 280 444 478 443]
 [304 225 308 123 286]
 [336 222 261 445 295]
 [293 191 243 449 390]]


In [274]:
print(array2_2)

[[191]
 [319]
 [334]
 [231]
 [351]
 [354]
 [226]
 [317]
 [226]
 [219]]


In [275]:
array2 = np.random.randint(100,500, size=(15,6))
print(array1)

[[172 356 234 434 474 191]
 [390 436 293 153 248 319]
 [277 479 214 195 285 334]
 [297 291 193 468 187 231]
 [392 359 440 285 148 351]
 [357 308 314 435 409 354]
 [242 280 444 478 443 226]
 [304 225 308 123 286 317]
 [336 222 261 445 295 226]
 [293 191 243 449 390 219]]


In [276]:
array2_1, array2_2, array2_3 = np.split(array1,[3,5], axis=1)
print(array2_1)

[[172 356 234]
 [390 436 293]
 [277 479 214]
 [297 291 193]
 [392 359 440]
 [357 308 314]
 [242 280 444]
 [304 225 308]
 [336 222 261]
 [293 191 243]]


In [277]:
print(array2_2)

[[434 474]
 [153 248]
 [195 285]
 [468 187]
 [285 148]
 [435 409]
 [478 443]
 [123 286]
 [445 295]
 [449 390]]


In [278]:
print(array2_3)

[[191]
 [319]
 [334]
 [231]
 [351]
 [354]
 [226]
 [317]
 [226]
 [219]]


In [279]:
array2 = np.random.randint(100,500, size=(15,6))
print(array1)

[[172 356 234 434 474 191]
 [390 436 293 153 248 319]
 [277 479 214 195 285 334]
 [297 291 193 468 187 231]
 [392 359 440 285 148 351]
 [357 308 314 435 409 354]
 [242 280 444 478 443 226]
 [304 225 308 123 286 317]
 [336 222 261 445 295 226]
 [293 191 243 449 390 219]]


In [280]:
array2_1, array2_2, array2_3 = np.split(array1,[3,5], axis=0)
print(array2_1)

[[172 356 234 434 474 191]
 [390 436 293 153 248 319]
 [277 479 214 195 285 334]]


In [281]:
print(array2_2)

[[297 291 193 468 187 231]
 [392 359 440 285 148 351]]


In [282]:
print(array2_3)

[[357 308 314 435 409 354]
 [242 280 444 478 443 226]
 [304 225 308 123 286 317]
 [336 222 261 445 295 226]
 [293 191 243 449 390 219]]


### mean


In [283]:
array1 = np.array([12,14,16,13,17])
mean = np.mean(array1)
print(mean)

14.4


In [284]:
median = np.median(array1)
print(median)

14.0


In [285]:
std = np.std(array1)
print(std)

1.8547236990991407


In [286]:
array_2 = np.random.randint(15,25, size=(6,4))
print(array_2)

[[22 19 21 18]
 [21 24 16 21]
 [15 23 21 19]
 [22 21 17 19]
 [20 24 18 15]
 [24 22 20 19]]


In [287]:
array_2_mean = np.mean(array_2, axis=0)
print(array_2_mean)

[20.66666667 22.16666667 18.83333333 18.5       ]


In [288]:
array_2_mean = np.mean(array_2, axis=1)
print(array_2_mean)

[20.   20.5  19.5  19.75 19.25 21.25]
