In [1]:
import numpy as np

### Learning array in numpy

In [5]:
### 1d array(one dimensoin array)

array_1d = np.array([1,2,3,4,5,6])
array_1d

array([1, 2, 3, 4, 5, 6])

### Two dimensional array

In [9]:
array_2d = np.array([[2,3,4],[1,2,3],[5,6,7]])
print(array_2d)

[[2 3 4]
 [1 2 3]
 [5 6 7]]


### Three dimentional array
-->collection of 2d array

In [11]:
array_3d =   np.array([[[1,2,3],
                        [2,4,5],
                        [4,5,6]],
                        [[2,3,4],
                        [5,6,7],
                        [8,9,7]]])
print(array_3d)

[[[1 2 3]
  [2 4 5]
  [4 5 6]]

 [[2 3 4]
  [5 6 7]
  [8 9 7]]]


### To check the dimension of array

In [15]:
array_3d.ndim

3

In [16]:
array_2d.ndim

2

In [17]:
array_1d.ndim

1

### One dimension array

In [19]:
array_1d = np.arange(1,101)
print(array_1d)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [20]:
array_1d = np.arange(1,101,2)
print(array_1d)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


### Linespace method

In [22]:
array_1d = np.linspace(1,10,10)
print(array_1d)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [23]:
array_1d = np.linspace(1,5,10)
print(array_1d)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
