In [82]:
import numpy as np

### Learning array in numpy

In [83]:
### 1d array(one dimensoin array)

array_1d = np.array([1,2,3,4,5,6])
array_1d

array([1, 2, 3, 4, 5, 6])

### Two dimensional array

In [84]:
array_2d = np.array([[2,3,4],[1,2,3],[5,6,7]])
print(array_2d)

[[2 3 4]
 [1 2 3]
 [5 6 7]]


### Three dimentional array
-->collection of 2d array

In [85]:
array_3d =   np.array([[[1,2,3],
                        [2,4,5],
                        [4,5,6]],
                        [[2,3,4],
                        [5,6,7],
                        [8,9,7]]])
print(array_3d)

[[[1 2 3]
  [2 4 5]
  [4 5 6]]

 [[2 3 4]
  [5 6 7]
  [8 9 7]]]


### To check the dimension of array

In [86]:
array_3d.ndim

3

In [87]:
array_2d.ndim

2

In [88]:
array_1d.ndim

1

### One dimension array using arange

In [89]:
array_1d = np.arange(1,11)
print(array_1d)

[ 1  2  3  4  5  6  7  8  9 10]


In [90]:
array_1d = np.arange(1,101,2)
print(array_1d)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


### Linespace method

In [91]:
array_1d = np.linspace(1,10,10)
print(array_1d)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [92]:
array_1d = np.linspace(1,5,10)
print(array_1d)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


### Size of array


In [93]:
np.size(array_1d)

10

In [94]:
np.size(array_2d)

9

In [95]:
np.size(array_3d)

18

### multiply and sum in array 

In [96]:
array_1 = np.array([1,2,3,4])
array_2 = np.array([5,2,3,4])
print(array_1 * array_2)

[ 5  4  9 16]


In [97]:
array_1 = np.array([1,2,3,4])
array_2 = np.array([5,2,3,4])
print(array_1 + array_2)

[6 4 6 8]


In [98]:
np.shape(array_1d)

(10,)

In [99]:
np.shape(array_2d)

(3, 3)

In [100]:
np.shape(array_3d)

(2, 3, 3)

### multiplication in numpy array


In [101]:
array1 = np.array([1,2,3])
array2 = np.array([2,3,4])
product = array1 @ array2
print(product)

20


### concatination in numpy array


In [102]:
array1 = np.array([1,2,3])
array2 = np.array([1,2,4])
array3 = np.concatenate((array1,array2))
print(array3)


[1 2 3 1 2 4]


### For two dimentional array

In [103]:
arr2d_1 = np.array([[1,2,3,4],
                    [5,6,7,8],
                    [6,9,7,3]])
arr2d_2 = np.array([[1,5,3,4],
                    [5,6,9,8],
                    [6,1,7,3]])
array3 = np.concatenate((arr2d_1,arr2d_2), axis=0)
print(array3)

[[1 2 3 4]
 [5 6 7 8]
 [6 9 7 3]
 [1 5 3 4]
 [5 6 9 8]
 [6 1 7 3]]


In [104]:
arr2d_1 = np.array([[1,2,3,4],
                    [5,6,7,8],
                    [6,9,7,3]])
arr2d_2 = np.array([[1,5,3,4],
                    [5,6,9,8],
                    [6,1,7,3]])
array3 = np.concatenate((arr2d_1,arr2d_2), axis=1)
print(array3)

[[1 2 3 4 1 5 3 4]
 [5 6 7 8 5 6 9 8]
 [6 9 7 3 6 1 7 3]]


### hstack (h= horizontal) and vstack (v= vertical) concatenation

In [105]:
arr1 = np.array([[1,2,3,1],[4,5,8,9]])
arr2 = np.array([[2,3,4,5]])
arr3 = np.vstack((arr1,arr2))
print(arr3)
arr4 = np.array([[4],
                [3]])


[[1 2 3 1]
 [4 5 8 9]
 [2 3 4 5]]


In [106]:
print(np.hstack((arr1,arr4)))

[[1 2 3 1 4]
 [4 5 8 9 3]]


### Slicing in numpy array

In [107]:
array1 = np.arange(1,11)
print(array1)
array2 = array1[2:5]
print(array2)

[ 1  2  3  4  5  6  7  8  9 10]
[3 4 5]


### For two dimensional array

In [108]:
array3 = np.array([[2,3,4,5],
                    [1,5,6,7],
                    [2,4,6,5]])
array3.shape


(3, 4)

In [109]:
array3.ndim

2

In [110]:
#it shows specific element from 2d array [row,col] slicing
print(array3[0,0])


2


In [111]:
# slicing
print(array3[1:3,1:3])


[[5 6]
 [4 6]]


In [112]:
print(array3[0:,1:3])

[[3 4]
 [5 6]
 [4 6]]


### reshaping array in numpy

In [113]:
array3.shape

(3, 4)

In [114]:
array3.reshape(4,3)

array([[2, 3, 4],
       [5, 1, 5],
       [6, 7, 2],
       [4, 6, 5]])

In [115]:
array3.reshape(6,2)

array([[2, 3],
       [4, 5],
       [1, 5],
       [6, 7],
       [2, 4],
       [6, 5]])

In [116]:
array3.reshape(3,4)

array([[2, 3, 4, 5],
       [1, 5, 6, 7],
       [2, 4, 6, 5]])

In [117]:
array3.reshape(12)

array([2, 3, 4, 5, 1, 5, 6, 7, 2, 4, 6, 5])

In [118]:
array3.reshape(2,3,2)

array([[[2, 3],
        [4, 5],
        [1, 5]],

       [[6, 7],
        [2, 4],
        [6, 5]]])

In [119]:
array5 = np.arange(1,101)
array5.reshape(5,20)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,
         34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
         54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
         74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
         94,  95,  96,  97,  98,  99, 100]])

### Random array in numpy


In [120]:
# rand() - gives the random values between 0 and 1 
# randint() - give the random integer value with in the specified range

In [121]:
array_1 = np.random.rand(4,6)

In [122]:
print(array_1)


[[0.68881347 0.57922538 0.77105535 0.38724147 0.44782906 0.43805919]
 [0.11023432 0.69639148 0.72488803 0.55529932 0.58414466 0.96040041]
 [0.41343202 0.79341449 0.98217538 0.26637046 0.18003955 0.45312992]
 [0.37748496 0.50961839 0.26896991 0.02647854 0.83575647 0.11655867]]


In [123]:
array_2 = np.random.rand(10)
print(array_2)

[0.06735224 0.00883743 0.66450459 0.9763084  0.71901009 0.02303883
 0.14348296 0.11632558 0.79330288 0.19936283]


### randint method

In [124]:
array_3 = np.random.randint(10,15, size=(7))
print(array_3)

[11 12 13 11 11 10 10]


### spliting in numpy array

In [125]:
array1 = np.random.randint(100,500, size=(15,6))
print(array1)

[[497 218 307 226 422 455]
 [377 173 220 166 168 464]
 [358 328 409 370 111 108]
 [142 103 310 254 429 274]
 [131 291 485 192 480 438]
 [266 217 462 386 151 448]
 [304 244 496 227 346 104]
 [477 142 375 445 408 171]
 [358 422 393 310 457 310]
 [425 177 446 476 201 202]
 [327 346 187 178 312 301]
 [479 117 213 452 370 465]
 [478 190 482 431 197 365]
 [389 105 352 183 281 200]
 [371 398 456 240 319 461]]


In [126]:
array1_1, array1_2, array1_3 = np.split(array1,3,axis=0)
print(array1_1)

[[497 218 307 226 422 455]
 [377 173 220 166 168 464]
 [358 328 409 370 111 108]
 [142 103 310 254 429 274]
 [131 291 485 192 480 438]]


In [127]:
print(array1_2)

[[266 217 462 386 151 448]
 [304 244 496 227 346 104]
 [477 142 375 445 408 171]
 [358 422 393 310 457 310]
 [425 177 446 476 201 202]]


In [128]:
print(array1_3)

[[327 346 187 178 312 301]
 [479 117 213 452 370 465]
 [478 190 482 431 197 365]
 [389 105 352 183 281 200]
 [371 398 456 240 319 461]]


### Columnwise spliting 

In [129]:
array1 = np.random.randint(100,500, size=(15,6))
print(array1)

[[271 303 178 271 230 355]
 [472 118 111 427 339 375]
 [483 341 263 286 402 396]
 [320 293 351 266 101 316]
 [497 123 209 181 380 321]
 [362 499 139 332 118 273]
 [495 406 187 375 320 220]
 [465 445 182 291 219 174]
 [200 234 276 315 238 348]
 [150 489 207 226 436 431]
 [499 296 411 100 313 383]
 [419 252 439 260 340 138]
 [132 212 329 261 334 396]
 [429 319 301 109 433 400]
 [245 415 309 308 377 421]]


In [130]:
array1_1, array1_2 = np.split(array1,2, axis=1)
print(array1_1)

[[271 303 178]
 [472 118 111]
 [483 341 263]
 [320 293 351]
 [497 123 209]
 [362 499 139]
 [495 406 187]
 [465 445 182]
 [200 234 276]
 [150 489 207]
 [499 296 411]
 [419 252 439]
 [132 212 329]
 [429 319 301]
 [245 415 309]]


In [131]:
print(array1_2)

[[271 230 355]
 [427 339 375]
 [286 402 396]
 [266 101 316]
 [181 380 321]
 [332 118 273]
 [375 320 220]
 [291 219 174]
 [315 238 348]
 [226 436 431]
 [100 313 383]
 [260 340 138]
 [261 334 396]
 [109 433 400]
 [308 377 421]]


In [132]:
array1 = np.random.randint(100,500, size=(10,6))
print(array1)

[[456 422 199 161 277 353]
 [148 191 262 207 357 136]
 [344 441 255 408 198 276]
 [264 315 435 157 212 100]
 [183 146 377 115 168 470]
 [398 141 328 269 484 293]
 [460 460 329 264 465 211]
 [222 210 356 227 116 210]
 [443 239 203 462 355 423]
 [353 239 488 211 398 245]]


In [133]:
array3 = np.concatenate((array1_1, array1_2),axis=1)
print(array3)

[[271 303 178 271 230 355]
 [472 118 111 427 339 375]
 [483 341 263 286 402 396]
 [320 293 351 266 101 316]
 [497 123 209 181 380 321]
 [362 499 139 332 118 273]
 [495 406 187 375 320 220]
 [465 445 182 291 219 174]
 [200 234 276 315 238 348]
 [150 489 207 226 436 431]
 [499 296 411 100 313 383]
 [419 252 439 260 340 138]
 [132 212 329 261 334 396]
 [429 319 301 109 433 400]
 [245 415 309 308 377 421]]


### spliting array by using indexing

In [134]:
array2 = np.random.randint(100,500, size=(15,6))
print(array1)

[[456 422 199 161 277 353]
 [148 191 262 207 357 136]
 [344 441 255 408 198 276]
 [264 315 435 157 212 100]
 [183 146 377 115 168 470]
 [398 141 328 269 484 293]
 [460 460 329 264 465 211]
 [222 210 356 227 116 210]
 [443 239 203 462 355 423]
 [353 239 488 211 398 245]]


In [135]:
array2_1, array2_2 = np.split(array1,[5], axis=1)
print(array2_1)


[[456 422 199 161 277]
 [148 191 262 207 357]
 [344 441 255 408 198]
 [264 315 435 157 212]
 [183 146 377 115 168]
 [398 141 328 269 484]
 [460 460 329 264 465]
 [222 210 356 227 116]
 [443 239 203 462 355]
 [353 239 488 211 398]]


In [136]:
print(array2_2)

[[353]
 [136]
 [276]
 [100]
 [470]
 [293]
 [211]
 [210]
 [423]
 [245]]


In [137]:
array2 = np.random.randint(100,500, size=(15,6))
print(array1)

[[456 422 199 161 277 353]
 [148 191 262 207 357 136]
 [344 441 255 408 198 276]
 [264 315 435 157 212 100]
 [183 146 377 115 168 470]
 [398 141 328 269 484 293]
 [460 460 329 264 465 211]
 [222 210 356 227 116 210]
 [443 239 203 462 355 423]
 [353 239 488 211 398 245]]


In [138]:
array2_1, array2_2, array2_3 = np.split(array1,[3,5], axis=1)
print(array2_1)

[[456 422 199]
 [148 191 262]
 [344 441 255]
 [264 315 435]
 [183 146 377]
 [398 141 328]
 [460 460 329]
 [222 210 356]
 [443 239 203]
 [353 239 488]]


In [139]:
print(array2_2)

[[161 277]
 [207 357]
 [408 198]
 [157 212]
 [115 168]
 [269 484]
 [264 465]
 [227 116]
 [462 355]
 [211 398]]


In [140]:
print(array2_3)

[[353]
 [136]
 [276]
 [100]
 [470]
 [293]
 [211]
 [210]
 [423]
 [245]]


In [141]:
array2 = np.random.randint(100,500, size=(15,6))
print(array1)

[[456 422 199 161 277 353]
 [148 191 262 207 357 136]
 [344 441 255 408 198 276]
 [264 315 435 157 212 100]
 [183 146 377 115 168 470]
 [398 141 328 269 484 293]
 [460 460 329 264 465 211]
 [222 210 356 227 116 210]
 [443 239 203 462 355 423]
 [353 239 488 211 398 245]]


In [142]:
array2_1, array2_2, array2_3 = np.split(array1,[3,5], axis=0)
print(array2_1)

[[456 422 199 161 277 353]
 [148 191 262 207 357 136]
 [344 441 255 408 198 276]]


In [143]:
print(array2_2)

[[264 315 435 157 212 100]
 [183 146 377 115 168 470]]


In [144]:
print(array2_3)

[[398 141 328 269 484 293]
 [460 460 329 264 465 211]
 [222 210 356 227 116 210]
 [443 239 203 462 355 423]
 [353 239 488 211 398 245]]


### mean


In [145]:
array1 = np.array([12,14,16,13,17])
mean = np.mean(array1)
print(mean)

14.4


In [146]:
median = np.median(array1)
print(median)

14.0


In [147]:
std = np.std(array1)
print(std)

1.8547236990991407


In [148]:
array_2 = np.random.randint(15,25, size=(6,4))
print(array_2)

[[17 15 16 17]
 [20 15 19 19]
 [24 22 21 22]
 [23 24 20 17]
 [17 24 17 24]
 [24 20 18 15]]


In [149]:
array_2_mean = np.mean(array_2, axis=0)
print(array_2_mean)

[20.83333333 20.         18.5        19.        ]


In [150]:
array_2_mean = np.mean(array_2, axis=1)
print(array_2_mean)

[16.25 18.25 22.25 21.   20.5  19.25]
